### ISSUE TITLE
Player list does not return SteamID

### ISSUE THREAD

**Issue by Trekkan** [KTTI465/PalWorld-RCON-GUI#11]
When doing a GetPlayers, SteamId is not returned.

**Comment by Trekkan** [comment]
No, they don't have multibyte characters (in this instance).  I've also seen some issues when returning larger amounts of data.  As an example servers that have 20-30 or so users online.  It looks like maybe the data is coming in multiple packets or something and getting cut off.

**Comment by KTTI465** [comment]
I've done some research and it seems that if the packet length is too long, it gets cut off by the server.
I'll try some of the various countermeasures that have been introduced.
